// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"
	"database/sql"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    organization_id,
    role_title,
    posting_url,
    salary_min,
    salary_max,
    work_location,
    applied_at,
    last_checked_at,
    notes
) VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), ?)
RETURNING
    id,
    organization_id,
    role_title,
    status,
    posting_url,
    salary_min,
    salary_max,
    work_location,
    applied_at,
    status_changed_at,
    last_checked_at,
    notes,
    created_at,
    updated_at
`

type CreateApplicationParams struct {
	OrganizationID int64
	RoleTitle      string
	PostingUrl     sql.NullString
	SalaryMin      sql.NullInt64
	SalaryMax      sql.NullInt64
	WorkLocation   string
	AppliedAt      sql.NullString
	Notes          sql.NullString
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.OrganizationID,
		arg.RoleTitle,
		arg.PostingUrl,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.WorkLocation,
		arg.AppliedAt,
		arg.Notes,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RoleTitle,
		&i.Status,
		&i.PostingUrl,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.WorkLocation,
		&i.AppliedAt,
		&i.StatusChangedAt,
		&i.LastCheckedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT
    applications.id,
    applications.organization_id,
    organizations.name AS organization_name,
    organizations.careers_url AS organization_careers_url,
    applications.role_title,
    applications.status,
    applications.posting_url,
    applications.salary_min,
    applications.salary_max,
    applications.work_location,
    applications.applied_at,
    applications.status_changed_at,
    applications.last_checked_at,
    applications.notes,
    applications.created_at,
    applications.updated_at
FROM applications
JOIN organizations ON organizations.id = applications.organization_id
ORDER BY applications.created_at DESC, applications.id DESC
`

type ListApplicationsRow struct {
	ID                     int64
	OrganizationID         int64
	OrganizationName       string
	OrganizationCareersUrl sql.NullString
	RoleTitle              string
	Status                 string
	PostingUrl             sql.NullString
	SalaryMin              sql.NullInt64
	SalaryMax              sql.NullInt64
	WorkLocation           string
	AppliedAt              sql.NullString
	StatusChangedAt        string
	LastCheckedAt          sql.NullString
	Notes                  sql.NullString
	CreatedAt              string
	UpdatedAt              string
}

func (q *Queries) ListApplications(ctx context.Context) ([]ListApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationCareersUrl,
			&i.RoleTitle,
			&i.Status,
			&i.PostingUrl,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.WorkLocation,
			&i.AppliedAt,
			&i.StatusChangedAt,
			&i.LastCheckedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markApplicationChecked = `-- name: MarkApplicationChecked :one
UPDATE applications
SET
    last_checked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
RETURNING
    id,
    organization_id,
    role_title,
    status,
    posting_url,
    salary_min,
    salary_max,
    work_location,
    applied_at,
    status_changed_at,
    last_checked_at,
    notes,
    created_at,
    updated_at
`

func (q *Queries) MarkApplicationChecked(ctx context.Context, id int64) (Application, error) {
	row := q.db.QueryRowContext(ctx, markApplicationChecked, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RoleTitle,
		&i.Status,
		&i.PostingUrl,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.WorkLocation,
		&i.AppliedAt,
		&i.StatusChangedAt,
		&i.LastCheckedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET
    organization_id = ?1,
    role_title = ?2,
    status_changed_at = CASE
        WHEN status <> ?3
            THEN strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
        ELSE status_changed_at
    END,
    status = ?3,
    posting_url = ?4,
    salary_min = ?5,
    salary_max = ?6,
    work_location = ?7,
    applied_at = ?8,
    notes = ?9,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?10
RETURNING
    id,
    organization_id,
    role_title,
    status,
    posting_url,
    salary_min,
    salary_max,
    work_location,
    applied_at,
    status_changed_at,
    last_checked_at,
    notes,
    created_at,
    updated_at
`

type UpdateApplicationParams struct {
	OrganizationID int64
	RoleTitle      string
	Status         string
	PostingUrl     sql.NullString
	SalaryMin      sql.NullInt64
	SalaryMax      sql.NullInt64
	WorkLocation   string
	AppliedAt      sql.NullString
	Notes          sql.NullString
	ID             int64
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplication,
		arg.OrganizationID,
		arg.RoleTitle,
		arg.Status,
		arg.PostingUrl,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.WorkLocation,
		arg.AppliedAt,
		arg.Notes,
		arg.ID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RoleTitle,
		&i.Status,
		&i.PostingUrl,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.WorkLocation,
		&i.AppliedAt,
		&i.StatusChangedAt,
		&i.LastCheckedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
