// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"
	"database/sql"
)

const listApplications = `-- name: ListApplications :many
SELECT
    applications.id,
    applications.organization_id,
    organizations.name AS organization_name,
    applications.role_title,
    applications.status,
    applications.posting_url,
    applications.salary_min,
    applications.salary_max,
    applications.work_location,
    applications.applied_at,
    applications.status_changed_at,
    applications.last_checked_at,
    applications.notes,
    applications.created_at,
    applications.updated_at
FROM applications
JOIN organizations ON organizations.id = applications.organization_id
ORDER BY applications.created_at DESC, applications.id DESC
`

type ListApplicationsRow struct {
	ID               int64
	OrganizationID   int64
	OrganizationName string
	RoleTitle        string
	Status           string
	PostingUrl       sql.NullString
	SalaryMin        sql.NullInt64
	SalaryMax        sql.NullInt64
	WorkLocation     string
	AppliedAt        sql.NullString
	StatusChangedAt  string
	LastCheckedAt    sql.NullString
	Notes            sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) ListApplications(ctx context.Context) ([]ListApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.RoleTitle,
			&i.Status,
			&i.PostingUrl,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.WorkLocation,
			&i.AppliedAt,
			&i.StatusChangedAt,
			&i.LastCheckedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
