// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Application struct {
	ID              int64
	OrganizationID  int64
	RoleTitle       string
	Status          string
	PostingUrl      sql.NullString
	SalaryMin       sql.NullInt64
	SalaryMax       sql.NullInt64
	WorkLocation    string
	AppliedAt       sql.NullString
	StatusChangedAt string
	LastCheckedAt   sql.NullString
	Notes           sql.NullString
	CreatedAt       string
	UpdatedAt       string
}

type Organization struct {
	ID         int64
	Name       string
	CareersUrl sql.NullString
	CreatedAt  string
	UpdatedAt  string
}

type Setting struct {
	ID              int64
	Name            string
	PortalCheckDays int64
}
