// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package database

import (
	"context"
)

const getOrCreateOrganization = `-- name: GetOrCreateOrganization :one
INSERT INTO organizations (name)
VALUES (?)
ON CONFLICT (name) DO UPDATE SET name = organizations.name
RETURNING
    id,
    name,
    careers_url,
    created_at,
    updated_at
`

func (q *Queries) GetOrCreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CareersUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
