// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_changes.sql

package database

import (
	"context"
)

const createStatusChange = `-- name: CreateStatusChange :exec
INSERT INTO application_status_changes (application_id, status, changed_at)
VALUES (?, ?, ?)
`

type CreateStatusChangeParams struct {
	ApplicationID int64
	Status        string
	ChangedAt     string
}

func (q *Queries) CreateStatusChange(ctx context.Context, arg CreateStatusChangeParams) error {
	_, err := q.db.ExecContext(ctx, createStatusChange, arg.ApplicationID, arg.Status, arg.ChangedAt)
	return err
}

const listStatusChanges = `-- name: ListStatusChanges :many
SELECT application_id, status, changed_at
FROM application_status_changes
ORDER BY application_id, changed_at, id
`

type ListStatusChangesRow struct {
	ApplicationID int64
	Status        string
	ChangedAt     string
}

func (q *Queries) ListStatusChanges(ctx context.Context) ([]ListStatusChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStatusChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatusChangesRow
	for rows.Next() {
		var i ListStatusChangesRow
		if err := rows.Scan(&i.ApplicationID, &i.Status, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordStatusChange = `-- name: RecordStatusChange :exec
INSERT INTO application_status_changes (application_id, status)
SELECT applications.id, ?1
FROM applications
WHERE applications.id = ?2
    AND applications.status <> ?1
`

type RecordStatusChangeParams struct {
	Status string
	ID     int64
}

// Runs before the application update in the same transaction; it records a row only when the status actually changes.
func (q *Queries) RecordStatusChange(ctx context.Context, arg RecordStatusChangeParams) error {
	_, err := q.db.ExecContext(ctx, recordStatusChange, arg.Status, arg.ID)
	return err
}
